### ISSUE TITLE
如果等待seajs加载完成后再加载css文件，页面会因重绘而闪动

### ISSUE THREAD

**Issue by andyforever** [seajs/seajs-css#6]
seajs一般都是在页面加载完成之后再加载，有没有更好的解决方案？

**Comment by army8735** [comment]
css不建议用js来加载，自己做combo服务。

**Comment by andyforever** [comment]
seajs-css插件有没有特殊的应用场景？

**Comment by army8735** [comment]
之所以抽离出来就是不推荐用js加载css，只是为了满足特定需求和兼容性才保留着。

**Comment by andyforever** [comment]
Thanks.This issue should be closed.
